// lang-es.js
const translations = {
  "title": "Optimizador de Dados KCD2",
  "selected_dice": "Dados Seleccionados",
  "remove_hint": "Click en × para eliminar dados",
  "simulation": "Simulación",
  "add_die": "Añadir",
  "clear": "Limpiar",
  "calculate": "Calcular Combinaciones",
  "how_we_choose": "¿Cómo elegimos las mejores combinaciones?",
  "top_combinations": "Mejores Combinaciones",
  "points": "ptos.",
  "save_preset": "Guardar Preset",
  "load_preset": "Cargar Preset",
  "delete_preset": "Eliminar Preset",
  "select_preset": "Seleccionar Preset",
  "preset_saved": "¡Preset guardado!",
  "no_dice_to_save": "¡No hay dados para guardar!",
  "confirm_delete": "¿Eliminar preset?",
  "simulation_steps": [
      "Calcula la puntuación de cada tirada considerando simples, tríos, múltiplos y escaleras",
      "Genera todas las combinaciones únicas de los dados seleccionados",
      "Ejecuta 1000 simulaciones por cada combinación",
      "Calcula la puntuación promedio de cada combinación",
      "Ordena las combinaciones por puntuación promedio de mayor a menor",
      "Muestra las 5 mejores combinaciones con detalles y puntuaciones"
  ],
  "no_dice_selected": "¡Selecciona dados primero!",
  "invalid_preset_name": "¡El nombre del preset no puede estar vacío!",
  "search_dice": "Buscar dados...",
  "simulation_error": "¡Error en la simulación!",
  "preset_name_placeholder": "Nombre del preset",
  "max_dice_error": "Máximo {MAX_DICE} dados permitidos por rendimiento",
  "preset_overwritten": "se ha sobrescrito",
  "exceed_message": "Has superado el límite de 30 dados",
};